### ISSUE TITLE
Include tag is not parsed for a resource type parameter

### ISSUE THREAD

**Issue by vovan-st** [raml-org/raml-java-parser#103]
The parser does not parse and include to external file with example if it is passed as parameter to resource type. Therefore, example of refactoring RAML file with using includes described in the [RAML tutorial](http://raml.org/developers/raml-200-tutorial#includes)  does not work:

```
/songs:
  type:
    collection:
      exampleCollection: !include jukebox-include-songs.sample
      exampleItem: !include jukebox-include-song-new.sample
```
Node tag (that is !include in this case) is ignored and the node is not resolved with IncludeResolver, but  only string value of the tag (that is a file path or name) is used while extracting resource references and cloning nodes. And later when resolving it using parameters it just set that string as parameter value.
Could you please help to resolve the issue with?
