### ISSUE TITLE
v2: how to access specific type informations (defined in *TypeDeclaration)?

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#110]
E.g. when `parameter.type()=='number'` how do I access `minimum` and `maximum`? 
Should `parameter` be castable to `NumberTypeDeclaration`? 
It seems that this is never possible.

**Comment by Boskiantonio** [comment]
I have similar problem. Is it possible (or will be) to get list of properties from Types declaration?

```
#%RAML 1.0
title: hola
types:
  User:
    type: object
    properties:
      name: string
      lastname: string
    example:
      name: Bob
      lastname: Marley

```
api.types().get(0).properties()

There is no properties method in org.raml.v2.internal.impl.commons.model.TypeDeclaration right now.
