### ISSUE TITLE
V2: Default value not being loaded for query parameter in Raml 0.8

### ISSUE THREAD

**Issue by diegostrubolini** [raml-org/raml-java-parser#119]
When having a Raml with the following query parameter (for example):
```
queryParameters:
  stock:
    default: 1
    required: false
```
The "defaultValue()" is returning null in the _Parameter_ class, it seems to work correctly with Raml 1.0, when asking the _defaultValue()_ to the _TypeDeclaration_ class.
Here is the full raml: [no-example-query-parameter.txt](https://github.com/raml-org/raml-java-parser/files/332514/no-example-query-parameter.txt)
