### ISSUE TITLE
[TCK] TC011 Annotations - java.lang.ClassCastException: org.raml.yagi.framework.nodes.snakeyaml.SYIntegerNode

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#121]
When parsing the following RAML:

```yaml
#%RAML 1.0
title: 22
types:
  Pet:
    properties:
      name: string
  Person:
    properties:
      []: Pet

  MapOfPerson:
    properties:
      []: Person
annotationTypes:
  hello:
    properties:
      persons: MapOfPerson
(hello):
   persons:
     156798654:
       Alice:
         name: stringValue

/d:
# annotations:
#   hello:
#     persons:
#       f:
# /resource:
#   get:
```
**Actual result:**
Exception in thread "main" java.lang.ClassCastException: org.raml.yagi.framework.nodes.snakeyaml.SYIntegerNode cannot be cast to org.raml.yagi.framework.nodes.StringNode
	at org.raml.yagi.framework.grammar.rule.MinLengthRule.apply(MinLengthRule.java:62)
	at org.raml.yagi.framework.grammar.rule.AllOfRule.apply(AllOfRule.java:98)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:102)
	at org.raml.yagi.framework.grammar.rule.FirstOfRule.apply(FirstOfRule.java:55)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:136)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:153)
	at org.raml.yagi.framework.phase.GrammarPhase.apply(GrammarPhase.java:38)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:88)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:73)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:78)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:69)
	at org.raml.v2.internal.impl.RamlValidator.validateRaml(RamlValidator.java:87)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:59)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:46)
	at org.raml.v2.internal.impl.RamlValidator.main(RamlValidator.java:117)

**Expected result:**

The RAML should be successfully parsed
