### ISSUE TITLE
Validate missing '{' in baseUri

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#124]
Parsing the following raml:
```yaml
#%RAML 1.0
title: Test
baseUri: http://{myapi.com
```

Actual result:
RAML is parsed 

Output: 
{
    "title": {
        "value": "Test"
    },
    "baseUri": {
        "value": "http://{myapi.com"
    }
}

Expected result:
Parser should validate missing '{'
