### ISSUE TITLE
[TCK] TC016 Examples - Error when using maxProperties

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#125]
When parsing the following RAML:

```yaml
#%RAML 1.0
title: Test API
types:
  MyType1:
    properties:
      lala: string
    maxProperties: 7
annotationTypes:
  MyAnnotationType1:
    properties:
      pp: MyType1
(MyAnnotationType1):
      pp:
        lala: lala
        xx: "2"
        xx2: "3"
```

**Actual result:**
Exception in thread "main" java.lang.ClassCastException: org.raml.yagi.framework.nodes.snakeyaml.SYObjectNode cannot be cast to org.raml.yagi.framework.nodes.StringNode
	at org.raml.yagi.framework.grammar.rule.MaxPropertiesRule.apply(MaxPropertiesRule.java:48)
	at org.raml.yagi.framework.grammar.rule.AllOfRule.apply(AllOfRule.java:98)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:136)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:153)
	at org.raml.yagi.framework.grammar.rule.AllOfRule.apply(AllOfRule.java:98)
	at org.raml.v2.internal.impl.v10.phase.AnnotationValidationPhase.apply(AnnotationValidationPhase.java:57)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:88)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:73)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:78)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:69)
	at org.raml.v2.internal.impl.RamlValidator.validateRaml(RamlValidator.java:87)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:59)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:46)
	at org.raml.v2.internal.impl.RamlValidator.main(RamlValidator.java:117)

**Expected result:**

If maxProperties >= actual properties the file should be correctly parsed
