### ISSUE TITLE
Empty traits not supported

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#127]
When parsing the following RAML , included in a parent file
```yaml
#%RAML 1.0 Library
traits:
  hello:
```
Actual result:

- Invalid root node SyNullNode. Expected : Mapping. [line=6, col=3]

Expected result:

RAML file should be parsed successfully
