### ISSUE TITLE
[TCK] TC007 Types - Change message when an array is invalid

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#128]
When elements of an array are from different type as the following example:
```yaml
#%RAML 1.0
title: API

types:
  SimpleUnion:
    type: string[] | number[]

  TypeWithUnionProps:
    type: object
    properties:
      unionArray1: SimpleUnion
      unionArray2: SimpleUnion
    example:
      unionArray1: [blah, 2, 3]
      unionArray2: [blah, blah, blah]
```
**Actual result:**
A list of all elements arbitrarily considered invalid are displayed:

- Invalid array element 2. [line=14, col=27]

- Invalid array element 3. [line=14, col=30]

**Expected result**

Display a message saying that the array is invalid or that the elements of the array are not valid, but do not list them
