### ISSUE TITLE
[TCK] TC013 Types - Support syntactic sugar for representing nullable properties using a union

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#129]
Parsing the following RAML
```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    properties:
      someProperty: SomeType?
    example:
        someProperty:
          someProperty:
            someProperty: null
```

**Actual result:**
	- Invalid reference 'SomeType?' [line=7, col=30]

**Expected result:**

The output should be the same as parsing the following raml

```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    properties:
      someProperty: SomeType | null
    example:
        someProperty:
          someProperty:
            someProperty: null
```
