### ISSUE TITLE
Pattern properties don't need to match all the key just a sub part

### ISSUE THREAD

**Issue by machaval** [raml-org/raml-java-parser#130]
This example should  validate 
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#additional-properties

```
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
    example:
      name: Santiago
      age: 40
      nick: El Lider
```
