### ISSUE TITLE
[TCK] TC025 Types- Types and schemas are mutually exclusive

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#131]
```yaml
#%RAML 1.0
title: Types 002.
version: v1
baseUri: https://example.com/raml
types:
  Player1: |
     {
       "type": "object",
       "properties": [
         {
           "name": "string"
         }
       ]
     }

schemas:
  Player2: |
     {
       "type": "object",
       "properties": [
         {
           "name": "string"
         }
       ]
     }
```
**Actual result:**

RAML is parsed successfully, with the following output:

```
{
    "title": {
        "value": "Types 002."
    },
    "version": {
        "value": "v1"
    },
    "baseUri": {
        "value": "https://example.com/raml"
    },
    "types": {
        "Player1": {
            "type": "{\n  \"type\": \"object\",\n  \"properties\": [\n    {\n      \"name\": \"string\"\n    }\n  ]\n}\n",
            "displayName": {
                "value": "Player1"
            }
        }
    },
    "schemas": {
        "Player2": {
            "type": "{\n  \"type\": \"object\",\n  \"properties\": [\n    {\n      \"name\": \"string\"\n    }\n  ]\n}",
            "displayName": {
                "value": "Player2"
            }
        }
    }
}
```
**Expected result:**

As spec says:

The "schemas" and "types" nodes are mutually exclusive and synonymous: processors MUST NOT allow both to be specified at the root-level of an API definition. We recommended using the "types" node instead of "schemas" because the schemas alias is deprecated and might be removed in a future RAML version.
