### ISSUE TITLE
Add support for an inline type declaration

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#132]
```yaml
#%RAML 1.0
title: TCK Sample. RAML 1.0 Types 003.
version: v1
baseUri: http://api.samplehost.com/{version}
/teams:
  get:
    body:
      application/xml:
        type:
          properties:
            prop1: string
            prop2: number
/teams2:
  get:
    body:
      application/xml:
        type: string
/teams3:
  get:
    body:
      application/xml:
        schema: string
/teams4:
  get:
    body:
      application/xml:
        schema: string
/teams5:
  get:
    body:
      application/xml:
        type: string
/teams6:
  get:
    body:
      application/xml:
        type: string
```

**Actual result:**
	- Invalid element {
properties: {
prop1: string,
prop2: number
}
}. [line=10, col=11]

**Expected result:**

type? A base type which the current type extends or just wraps. The value of a type node MUST be either a) the name of a user-defined type or b) the name of a built-in RAML data type (object, array, or one of the scalar types) or c) an inline type declaration.
