### ISSUE TITLE
Property Override - A property cannot be changed to optional

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#134]
Input:
```yaml
#%RAML 1.0

title: test

types:
  PropertyType1:
    type: string
    minLength: 0
  PropertyType2:
    type: PropertyType1
    maxLength: 5
  Type1:
    properties:
      testProperty: PropertyType1
  Type2:
    type: Type1
    properties:
      testProperty?: PropertyType2
```
**Actual result:**
```
{
    "title": {
        "value": "test"
    },
    "types": {
        "PropertyType1": {
            "type": "string",
            "minLength": 0,
            "displayName": {
                "value": "PropertyType1"
            }
        },
        "PropertyType2": {
            "type": "PropertyType1",
            "maxLength": 5,
            "displayName": {
                "value": "PropertyType2"
            }
        },
        "Type1": {
            "properties": {
                "testProperty": {
                    "type": "PropertyType1",
                    "displayName": {
                        "value": "testProperty"
                    }
                }
            },
            "type": "object",
            "displayName": {
                "value": "Type1"
            }
        },
        "Type2": {
            "type": "Type1",
            "properties": {
                "testProperty?": {
                    "type": "PropertyType2",
                    "displayName": {
                        "value": "testProperty?"
                    }
                }
            },
            "displayName": {
                "value": "Type2"
            }
        }
    }
}
```

**Expected result:**
A sub-type can override properties of its parent type with the following restrictions: 1) a required property in the parent type cannot be changed to optional in the sub-type
