### ISSUE TITLE
Type Override- Facet names validation

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#135]
```yaml
#%RAML 1.0
title: test
types:
  SuperType:
    facets:
      test: string
  SubType:
    type: SuperType
    facets:
      test: string
```

**Actual result:**
```yaml 
{
    "title": {
        "value": "test"
    },
    "types": {
        "SuperType": {
            "facets": {
                "test": {
                    "type": "string",
                    "displayName": {
                        "value": "test"
                    }
                }
            },
            "type": "string",
            "displayName": {
                "value": "SuperType"
            }
        },
        "SubType": {
            "type": "SuperType",
            "facets": {
                "test": {
                    "type": "string",
                    "displayName": {
                        "value": "test"
                    }
                }
            },
            "displayName": {
                "value": "SubType"
            }
        }
    }
}
 ```

**Expected result:**
User-defined facet names on a type MUST NOT match built-in facets on that type, nor facet names of any ancestor type in the inheritance chain of the type
