### ISSUE TITLE
V2: Including external types in YAML is Invalid

### ISSUE THREAD

**Issue by diegostrubolini** [raml-org/raml-java-parser#140]
Having the following RAML:
```
#%RAML 1.0
title: Example API
types: !include user.type
/users/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: User
```

and a _user.type_ file with the following:
```
User:
    type: object
    properties:
      firstname: string
      lastname:  string
      age: number
```
is parsed as invalid with the validation result being: Invalid element User:.. [line=3, col=8]]
This works correctly when including external json-schemas for a specific type, but trying to include types in a separate file seems to fail
