### ISSUE TITLE
Invalid mediaType should be validated

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#145]
Input:
```yaml
#%RAML 1.0
title: Test Api
mediaType: someStringvalue
```

Output:
```
{
    "title": {
        "value": "Test Api"
    },
    "mediaType": "someStringvalue"
}
```

Expected result:
Invalid mediaType should be validated
