### ISSUE TITLE
Valid Union types example is being incorrectly validated

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#146]
**Input:**
```yaml 
#%RAML 1.0
title: API

types:
  SimpleType1:
    properties:
      property1: string
      property2: string

  SimpleType2:
    properties:
      property1: number
      property2: number

  SimpleUnion:
    type: SimpleType1 | SimpleType2

  TypeWithUnionProps:
    type: object
    properties:
      unionArray: SimpleUnion[]
    example:
      unionArray:
        -
          property1: 1
          property2: 2
        -
          property1: 1
          property2: 2
```
**Output:**

```

	- Invalid type Integer, expected String [line=25, col=22]

	- Invalid type Integer, expected String [line=26, col=22]

	- Invalid type Integer, expected String [line=28, col=22]

	- Invalid type Integer, expected String [line=29, col=22]

```

Expected result:

As the given example corresponds with SimpleType2 it should be correctly parsed
