### ISSUE TITLE
Validate incoherence between maximum and minimum

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#147]
**Input**: 

```yaml 
#%RAML 1.0
title: Some API

types:
    SomeType:
        type: number
        maximum: 1
        minimum: 10
```
**Output**:
```
{
    "title": {
        "value": "Some API"
    },
    "types": {
        "SomeType": {
            "type": "number",
            "maximum": 1,
            "minimum": 10,
            "displayName": {
                "value": "SomeType"
            }
        }
    }
}
```

**Expected result:**

As **maximum** is lower than **minimum** it should be validated
