### ISSUE TITLE
minProperties is not being validated

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#148]
**Input:**
```yaml
#%RAML 1.0
title: My API With Types
types:
  Initial_comments:
    type: object
    minProperties: 2
    properties:
      comment_id?: number
      initial_comments?: string
    example:
      initial_comments: mm
```

**Output:**
```
{
    "title": {
        "value": "My API With Types"
    },
    "types": {
        "Initial_comments": {
            "type": "object",
            "minProperties": 2,
            "properties": {
                "comment_id?": {
                    "type": "number",
                    "displayName": {
                        "value": "comment_id?"
                    }
                },
                "initial_comments?": {
                    "type": "string",
                    "displayName": {
                        "value": "initial_comments?"
                    }
                }
            },
            "example": {
                "initial_comments": "mm"
            },
            "displayName": {
                "value": "Initial_comments"
            }
        }
    }
}
```

**Expected result:** 
As minProperties is set to 2, the example is not correct, it has only one property, and it should be validated
