### ISSUE TITLE
Example format should correspond to the format defined in the type

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#149]
**Input**:

```yaml
#%RAML 1.0
title: A
types:
  mySchema: |
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Product",
      "description": "A product from Acme's catalog",
      "type": "object",
      "properties": {
          "id": {
              "description": "The unique identifier for a product",
              "type": "string"
          }
      },
      "required": ["id"]
    }

  z2:
    properties:
      c: mySchema
    example:
      c: 4
```

**Output:**

```
1 error found:

	- Error validating JSON. Error: {
object has missing required properties (["id"])
} [line=23, col=10]
```

**Expected result:**

Even when the message has sense, the given example is not valid, because is not a valid json
