### ISSUE TITLE
Accessing the type name of a property

### ISSUE THREAD

**Issue by hwellmann** [raml-org/raml-java-parser#153]
Working with the v2 parser and a RAML 1.0 spec, I'm not sure how to access the name of the type of an object type property.

Example:

````
#%RAML 1.0
title: API with Types
types:
 Address:
   type: object
   properties:
     city: string
     street: string 
 User:
   type: object
   properties:
     firstname:
       type: string
     lastname:
       type: string
     homeAddress:
       type: Address  
````

Using `Api.types()`, I can get hold of the `TypeDeclaration` of `User`. 

After a downcast, `ObjectTypeDeclaration.properties()` gives me access to another `TypeDeclaration` for the `homeAddress` property.

Now the problem is that the `name()` method of that declaration returns the property name `homeAddress` and not the type name `Address`.

Is there way to access both the property name and the type name without using any internal implementation classes?
