### ISSUE TITLE
Invalid validation of a pattern property

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#171]
```yaml
#%RAML 1.0
title: Testing with Jonathan
mediaType: application/json
types:
  URL:
  User:
    properties:
      firstName: string
      lastName: string
  Brand:
    properties:
      name: string
      logo: URL
      followers: User[]
      [^X\-]:
        type: any
    example:
      name: Brandicted
      logo: http://www.domain.com/logo.gif
      followers:
        - firstName: Fred
          lastName: Armand
        - firstName: Joan
          lastName: Rivers
```

**Actual result:**

	- Unexpected key 'Array[^X\-]' [line=15, col=7]

**Expected result:**

A valid example should be "X-e"

This raml should be valid
