### ISSUE TITLE
Validate setting nodes are mandatory

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#172]
```yaml
#%RAML 1.0
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securitySchemes:
  oauth_1_0:
    description: |
      Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 1.0
    settings:
```

```yaml
#%RAML 1.0
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securitySchemes:
  oauth_1_0:
    description: |
      Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    settings:

```
**Actual result:**

Ramls are parsed successfully 

**Expected result**

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#settings
