### ISSUE TITLE
Accept decimal values in number type facets

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#174]
With the following RAML:

```yaml
#%RAML 1.0
title: Some API

types:
    MyCustomType:
      type: number
      minimum: 2.5
      maximum: 9.30
      multipleOf: 3.4
      example: 6.8
```

**The parser is giving the following output:**

```
3 errors found:
	- Invalid element 2.5. [line=7, col=16]
	- Invalid element 9.30. [line=8, col=16]
	- Invalid element 3.4. [line=9, col=19]
```

**Expected result:**

If the user is defining a type which inherits from Number type, it MUST accept decimal values in its facets.
