### ISSUE TITLE
Parser should allow add new annotationTypes, Types, Schemas and override examples

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#175]
```yaml
#%RAML 1.0 Overlay
title: Pet Shop Overlay
extends: api.raml

annotationTypes:
  Test3:
    properties:
      name: string
```

```yaml
#%RAML 1.0
#api.raml
title: Pet shop

```

Actual Result:
Invalid overlay node. Cannot override node: annotationTypes

Expected result:
as spec says:
annotationTypes:	The merged tree can include new annotation types or new values for existing annotation types, as long as all annotations in the merged API definition validate against the annotation types in the merged tree.
