### ISSUE TITLE
Parser must not allow add or override resources

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#176]
```yaml
#%RAML 1.0
#api.raml
title: test

/resource:
  displayName: "Test"

```

```yaml

#%RAML 1.0 Overlay
title: Overlay2
extends: api.raml

/resource:
  displayName: "Test3"
/anotherResource:

```
**Actual result:**

No errors

**Expected result:**

An overlay adds or overrides nodes of a RAML API definition while **preserving its behavioral**, functional aspects. **Certain nodes of a RAML API definition specify the behavior of an API: its resources**, methods, parameters, bodies, responses, and so on

**Comment by svacas** [comment]
I'm getting the following error with your example:
`"Invalid overlay node. Cannot override node: /anotherResource"`

**Comment by evangelina** [comment]
I could reproduce it with the following RAML configuration:

```yaml
#%RAML 1.0
#input.raml
title: test

/resource:
  displayName: "Test"
```

```yaml
#%RAML 1.0 Overlay
title: Overlay
extends: input.raml

/resource:
  displayName: "Test2"
```

```yaml
#%RAML 1.0 Overlay
title: Overlay2
extends: input.raml

/resource:
  displayName: "Test3"
/anotherResource:
```
