### ISSUE TITLE
Format: double is marked as invalid

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#177]
```yaml
#%RAML 1.0
title: API Gateway Test API
version: 1.0.0
baseUri: https://api.uber.com
mediaType: application/json
securitySchemes:
  key:
    type: Pass Through
    describedBy:
      headers:
        x-api-key:
/products:
  displayName: Product Types
  description: |
    The Products endpoint returns information about the *Uber* products
    offered at a given location. The response includes the display name
    and other details about each product, and lists the products in the
    proper display order.
  get:
    queryParameters:
      latitude:
        type: number
        format: double
        required: true
        description: Latitude component of location
      longitude:
        type: number
        format: double
        required: true
        description: Longitude component of location
```

Actual result:

	- Invalid element double. [line=23, col=17]

	- Invalid element double. [line=28, col=17]

Expected result:

format?	The format of the value. The value MUST be one of the following: int32, int64, int, long, float, double, int16, int8
