### ISSUE TITLE
displayName should be supported by overlays

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-java-parser#181]
`displayName` was missing in the list of fields that can be overlaid and it should be added

**Comment by eleonoraortega** [comment]
```yaml
#%RAML 1.0
#api.raml
title: hybrid-rest-services
version: 0.4
mediaType: application/json
securedBy: x-ttt
protocols: HTTP
securitySchemes:
   x-ttt:
      type: Digest Authentication

baseUri: https://anypoint.mulesoft.com/hybrid/api/v1
traits:
   env-org-pair:
      displayName: masterDisplayName
resourceTypes:
   servers-collection:
/servers:
  is: env-org-pair
  securedBy: x-ttt

```

```yaml
#%RAML 1.0 Overlay
#newoverlay.raml
title: Extension
extends: api.raml
traits:
  env-org-pair:
      displayName: overlayDisplayName

```
