### ISSUE TITLE
Invalid element with multiple inheritance example

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#184]
The following RAML:

```yaml
#%RAML 1.0
title: Mulitple Inheritance using the types

# Objective: This RAML illustrates an example of using multiple inheritance with the same types and facets applied
# Expected result: no error

# tags: multiple inheritance, types, facets

types:
  Number1:
    type: number
    minimum: 4
  Number2:
    type: number
    maximum: 10
  Number3: [ Number1, Number2]
```

Returns this error:

> Invalid element Array[Number1,Number2].

If the RAML is modified to the following it works as expected 

```yaml
types:
  Number1:
    type: number
    minimum: 4
  Number2:
    type: number
    maximum: 10
  Number3: 
    type: [ Number1, Number2]
```
