### ISSUE TITLE
The parser shouldn't fail if the included file is empty

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#185]
With the given RAML, if the users or user raml files included are empty, the parser fails with an Include file is empty error message.

```yaml
title: Example API
version: v1
mediaType: application/json
types:
  Users: !include types/users.raml
  User:  !include types/user.raml
```

users.raml
```yaml
#%RAML 1.0 DataType
```
