### ISSUE TITLE
wrapped XML facet not working as expected

### ISSUE THREAD

**Issue by moliva** [raml-org/raml-java-parser#189]
Current implementation generates a schema for `wrapped: false` at `friends` level that omits the wrapping of the inner type of the array instead of the wrapper element. The following RAML:
```raml
#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friends: Friend[]
  Friend:
    type: object
    properties:
      name: string
```
Generates an schema for the following __wrong__ example:
```xml
<root>
  <name>robert</name>
  <friends>
    <name>daenerys</name>
  </friends>
  <friends>
    <name>stannis</name>
  </friends>
  <friends>
    <name>arya</name>
  </friends>
</root>
```
Instead of the __expected__ one:
```xml
<root>
  <name>robert</name>
  <Friend>
    <name>daenerys</name>
  </Friend>
  <Friend>
    <name>stannis</name>
  </Friend>
  <Friend>
    <name>arya</name>
  </Friend>
</root>
```

Something similar happens to `wrapped: true`, for the fore mentioned RAML accepting this __wrong__ example:
```xml
<root>
  <name>robert</name>
  <friends>
    <Friend>
        <name>stannis</name>
    </Friend>
  </friends>
  <friends>
    <Friend>
      <name>daenerys</name>
    </Friend>
  </friends>
</root>
```
Instead of the __expected__ one:
```xml
<root>
  <name>robert</name>
  <friends>
    <Friend>
        <name>stannis</name>
    </Friend>
    <Friend>
      <name>daenerys</name>
    </Friend>
  </friends>
</root>
```

**Comment by eleonoraortega** [comment]
#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friends:
        type: Friend[]
        xml:
          wrapped: true # o false (por defecto false)
  Friend:
    type: object
    properties:
      name: string

**Comment by eleonoraortega** [comment]
example 1: 
```yaml
#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friends: Friend[]
    additionalProperties: false
    example: |
      <root>
        <name>robert</name>
        <Friend>
          <name>daenerys</name>
        </Friend>
        <Friend>
          <name>stannis</name>
        </Friend>
        <Friend>
          <name>arya</name>
        </Friend>
      </root>
  Friend:
    type: object
    properties:
      name: string
```
