### ISSUE TITLE
An absolute https URI should be supported as a valid authorization grant

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#193]
Based on the spec, an https URI should be supported as a valid authorization grant: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#oauth-20. 

The following RAML should be supported:

```yaml
#%RAML 1.0
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securitySchemes:
  oauth_2_0:
    description: |
      Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    settings:
      authorizationUri: https://www.dropbox.com/1/oauth2/authorize
      accessTokenUri: https://api.dropbox.com/1/oauth2/token
      authorizationGrants: [ authorization_code, password, client_credentials, implicit, 'https://example.com' ]
```
