### ISSUE TITLE
Parser doesn't detect recursion and throws a StackOverflowException

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#198]
The following raml files cause a stack overflow:

```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    type: SomeType[]
```

```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    type: SomeType
```

```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    type: OneMoreType

  AnotherType:
    type: SomeType

  OneMoreType:
    type: AnotherType
```

```yaml
#%RAML 1.0
title: API

types:
  SomeType:
    type: object | SomeUnion

  SomeUnion:
    type: AnotherType[] | OneMoreType[]

  AnotherType:
    type: SomeType

  OneMoreType:
    type: AnotherType
```
