### ISSUE TITLE
Validate conflicts when overriding a property type

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#200]
```yaml

#%RAML 1.0

title: test

types:
  PropertyType1:
    properties:
      name: string
  PropertyType2:
    type: PropertyType1
    properties:
      name2: string
  PropertyType3:
    properties:
      name: boolean
  Type1:
    properties:
      testProperty: PropertyType1
  Type2:
    type: Type1
    properties:
      testProperty: PropertyType3
```

**Actual result:**

No errors

**Expected result:**

As name is a property defined as boolean in PropertyType3 and as string in PropertyType1, the result of Type2 should be validated with an error
