### ISSUE TITLE
Can't obtain optional QueryParameter attributes minLength, maxLength, pattern, mininum and maximum

### ISSUE THREAD

**Issue by aweisser** [raml-org/raml-java-parser#203]
In v2 the `Method.queryParameters()` just returns Proxy instances that reflects the generic `Parameter` class. Even If I define a query parameter with `type: string`. I would expect the more specific `StringTypeDeclaration` type, so that I can access the additional attributes like `minLength` or `maxLength` ...

How can I optain those attributes?

Here's my raml

```
#%RAML 0.8
title: myapi
baseUri: /

/base:
  /endpointWithGet:
    get:
      description: "A description of endpointWithGet"
      queryParameters:
        param1:
          type: string
          minLength: 1
          maxLength: 100
```
