### ISSUE TITLE
Default type of QueryParameter in v2 should be string

### ISSUE THREAD

**Issue by aweisser** [raml-org/raml-java-parser#204]
The raml spec 0.8 says 

> If type is not specified, it defaults to string.

If you don't specify a `type: ` for your query parameter the v2 parser (for raml v.0.8) uses null as a default (`Parameter.type() returns null`).

Here's my raml

```
#%RAML 0.8
title: myapi
baseUri: /

/base:
  /endpointWithGet:
    get:
      queryParameters:
        param1:  ## default type should be string
```
