### ISSUE TITLE
Getting "Missing required field 'extends'" error

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#205]
The following RAML returns a Missing required field "extends" error:

input.raml
```yaml
#%RAML 1.0 Extension
title: Extension
extends: overlay.raml

/resource:
  displayName: "Test3"
/anotherResource:
```

overlay.raml
```yaml
#%RAML 1.0 Overlay
title: Overlay
extends: master.raml

/resource:
  displayName: "Test2"
```

master.raml
```yaml
#%RAML 1.0
title: test

/resource:
  displayName: "Test"
```
