### ISSUE TITLE
Pattern is not being enforced

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#212]
The following RAML is not returning an ERROR:

```yaml
#%RAML 1.0
title: Test named parameters
types:
  dept_code:
    pattern: ^\d+\-\w+$

traits:
  chargeable:
    headers:
      X-Dept:
        type: dept_code[]
        examples:
          one_dept:
            - 230-OCTO
            - InvalidHere
```
