### ISSUE TITLE
Getting a RuntimeException

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#213]
Parsing the following RAML produces a `Merging not supported for nodes of type SYNullNode and SYNullNode` error

```yaml
#%RAML 1.0
title: hybrid-rest-services
version: 0.4
mediaType: application/json
securedBy: x-ttt
protocols: HTTP
securitySchemes:
   x-ttt:
      type: Digest Authentication

baseUri: https://anypoint.mulesoft.com/hybrid/api/v1
traits:
   env-org-pair:
resourceTypes:
   servers-collection:
/servers:
  is: env-org-pair
  securedBy: x-ttt
```

```yaml
#%RAML 1.0 Overlay
title: Extension
extends: api.raml
traits:
  env-org-pair:
```
