### ISSUE TITLE
Getting invalid overlay node, cannot override annotation

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#214]
The following RAML fails with `Invalid overlay node. Cannot override node: (Test3)` error:

```yaml
#%RAML 1.0
title: Pet shop

traits:
  FilterableByPrice:
    queryParameters:
      priceLessThen?:
        type: number
      priceMoreThen?:
        type: number
    headers:
```

```yaml
#%RAML 1.0 Overlay
title: blah
extends: api.raml
annotationTypes:
  Test3:
    properties:
      name: string
traits:
  FilterableByPrice:
    (Test3):
      name: Blah
```
