### ISSUE TITLE
Error on trait with parameters

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-java-parser#215]
Parsing the following RAML is returning

```json
Invalid element {
application/json: {
example: {
  "prop": "value"
}

}
}
```

```yaml

#%RAML 1.0
title: Trait
version: v1
baseUri: http://api.samplehost.com
traits:
  trait1:
    queryParameters:
      param1: <<type1>>
    body: <<body1>>

/resource:
  get:
    is:
      - trait1:
          type1: number
          body1:
            application/json:
              example: |
                {
                  "prop": "value"
                }
```
