### ISSUE TITLE
V2: Raml 0.8 query parameters and headers should return default "required" value

### ISSUE THREAD

**Issue by diegostrubolini** [raml-org/raml-java-parser#216]
When declaring a query parameter or a header without specifying a boolean value for the **required** attribute, the _required()_ method returns null. It should return the default boolean value like the Raml 1.0 does.
Example:
```
      queryParameters:
        airline:
          description: The requested airline for the flight
          example: all
```
