### ISSUE TITLE
Cannot overlay documentation

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#220]
```yaml
#%RAML 1.0 Overlay
title: Slave RAML
extends: master.raml


documentation:
  - title: Introduction
    content: Automated access to books
  - title: Licensing
    content: Please respect copyrights on our books.
```

```yaml

#%RAML 1.0
title: Master RAML
#master.raml
/elements:
  get:
    responses:
      200:

```

Actual error:

	- Invalid overlay node. Cannot override node: documentation [line=7, col=3]

Expected result:

It is allowed to add Documentation by an overlay
