### ISSUE TITLE
Format facet is not restricting number values

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#221]
Parsing the following RAML:

```yaml
#%RAML 1.0
title: Test API
types:
  orders:
    properties:
      Priority:
        type: number
        format: int16
/resource:
  post:
    body:
      application/json:
        type: orders
        example:
          Priority: 3.5
```

_Priority_ is defined as:
``` yaml
type: number
format: int16
```

**Expected result:**
The example _3.5_ in the post request is invalid. While the type is defined as a number value, the format restricts it to be an integer.

Current result:
The RAML is parsed successfully
