### ISSUE TITLE
wrapped XML facet not working with additionalProperties

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#223]
Parsing the following raml:
```yaml
#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friends: 
        type: Friend[]
        xml:
          wrapped: false
    example: |
      <root>
        <name>robert</name>
        <Friend>
          <name>daenerys</name>
        </Friend>
        <Friend>
          <name>stannis</name>
        </Friend>
        <Friend>
          <name>arya</name>
        </Friend>
      </root>
  Friend:
    type: object
    properties:
      name: string
```

Actual result:
	- Error validating XML. Error: cos-nonambig: "http://validationnamespace.raml.org":Friend and WC[##any] (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles. [line=11, col=14]

Expected result:

raml should be parsed successfully

Note: set     additionalProperties: false

And it works
