### ISSUE TITLE
Including files is not working properly on Windows

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#227]
Having the following context in a Windows system:

A folder with two files on it:
- `main.raml`
- `common-schema.raml` (included in `main.raml`)

Where `main.raml` is:

``` yaml
#%RAML 0.8
title: Example API
baseUri: https://www.example.com/
protocols: [HTTPS]

schemas:
  - !include common-schema.raml

```

and `common-schema.raml` is:

``` yaml
getSearchResponse: |
       {
       }
```

**Actual result:**
The parsing process its failing, as it cannot find the `common-schema.raml` file.

**Expected result:**
The parsing must be done successfully.
