### ISSUE TITLE
Security scheme type is specified as required parser allows null

### ISSUE THREAD

**Issue by quilicicf** [raml-org/raml-java-parser#234]
### Issue

The requiredness of the field `type` in security schemes is not enforced by the parser.

### [Spec pointer](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#security-scheme-declaration)

The row for `type` in the table doesn't end with `?` which if I'm not mistaken means it's required.

#### RAML file

```yaml
#%RAML 1.0

title: My API title
securitySchemes:
  custom_without_type:
    description: Should have a type defined
```

#### Java file

```java
package com.restlet.definitions.raml10.reader;

import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;

import static org.junit.Assert.fail;

public class Test {

    @org.junit.Test
    public void test() throws Exception {
        String savedRamlLocation = Test.class.getResource("fileName").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);
        if (ramlModelResult.hasErrors()) {
            return;
        }

        fail("Should not pass parser validation");
    }
}
```
