### ISSUE TITLE
URI parameter of type file

### ISSUE THREAD

**Issue by quilicicf** [raml-org/raml-java-parser#239]
### Issue

URI parameters should never be of type file unless I'm mistaken.

#### RAML file

```yaml
#%RAML 1.0

title: My API title
/fileInUriParam/{file}:
  uriParameters:
    file: file
```

#### Java file

```java
package com.restlet.definitions.raml10.reader;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;
import org.raml.v2.api.model.v10.api.Api;

import static org.junit.Assert.fail;

public class Test {

    @org.junit.Test
    public void test() throws Exception {
        String savedRamlLocation = Test.class.getResource("fileName").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);
        if (ramlModelResult.hasErrors()) {
            return;
        }

        fail("Should not pass parser validation");
    }
}
```
