### ISSUE TITLE
Schema validation in request should give more information

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#247]
Taking the following RAML as an example:

``` yaml
#%RAML 1.0
title: Example
baseUri: http://base.uri/
schemas:
    - UserJson: |
          {
             "$schema": "http://json-schema.org/draft-04/schema",
             "type": "object",
             "properties": {
               "firstname":  { "type": "string" },
               "lastname":  { "type": "string" },
               "age":  { "type": "integer" }
             },
             "required": [ "firstname", "lastname" ]
          }

/endpoint:
    post:
        body:
            application/json:
                schema: UserJson
                example: 
```

**Expected result**
When the parser validates an example in `/endpoint` against the schema previously defined, it should give more information about where in the example the error occurred, e.g. the key.

**Actual result:**
The parser is only giving a simple message that the example is wrong.
