### ISSUE TITLE
Type declaration type() method returns "null_AnonymousType" when including DataType fragment.

### ISSUE THREAD

**Issue by constint** [raml-org/raml-java-parser#255]
## Affects [1.0.0](https://github.com/raml-org/raml-java-parser/tree/1.0.0)

**Issue**
Given the following example, the type() method returns "null_AnonymousType" for type 'stringType'
## How to reproduce

`file api.ram`

``` yaml
#%RAML 1.0
title: DataType Include Example

types:
  stringType:
    type: !include dataTypeFragment.raml

```

`file dataTypeFragment.raml`

``` yaml
#%RAML 1.0 DataType

type: string

```

**Java File**

``` java
import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;

public class Test {

    @org.junit.Test
    public void testRaml10Import() throws Exception {

        String savedRamlLocation = Test.class.getResource("your/path/api.raml").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);

        Api api= ramlModelResult.getApiV10();
        assertEquals(api.types().get(0).type(), "string");
    }
}
```
