### ISSUE TITLE
SecuritySchemes doesn't support queryString in describedBy

### ISSUE THREAD

**Issue by constint** [raml-org/raml-java-parser#256]
## Affects [1.0.0](https://github.com/raml-org/raml-java-parser/tree/1.0.0)

**Issue**
The following example produces the error:
```
---
- message: "Unexpected key 'queryString'. Options are : \"description\" or \"displayName\"\
    \ or \"headers\" or \"queryParameters\" or \"responses\" or /\\((.+)\\)/"
```

## How to reproduce
`file api.ram`
```yaml
#%RAML 1.0
title: Api

securitySchemes:
  custom_with_query_param:
    type: x-custom
    describedBy:
      queryString:
        properties:
          authQueryParam: string
```

**Java File**
```java
import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;

public class Test {

    @org.junit.Test
    public void testRaml10Import() throws Exception {

        String savedRamlLocation = Test.class.getResource("your/path/api.raml").toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);
        assertFalse(ramlModelResult.hasErrors());
    }
}
```
