### ISSUE TITLE
Add path when creating a ValidationResult error

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#257]
When parsing a RAML file containing errors, and then asking for `ValidationResults`, each validation result is only displaying the error message, but is not giving any further information about where in the RAML file the problem is.

For example, using the following RAML file:

``` yaml
#%RAML 1.0
title: API with Examples
types:
  User:
    type: object
    properties:
      name:
        type: string
        minLength: 5
      lastname:
        type: string
        maxLength: 5
    example:
        value:
          name: Bob
          lastname: Marley
```

In the following test case:

``` Java
RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(input);
if (ramlModelResult.hasErrors())
{
    for (ValidationResult validationResult : ramlModelResult.getValidationResults())
    {
        System.out.println(validationResult.getMessage());
    }
}
```

**Output**

```
Expected min length 5
Expected max length 5
```

**Expected Output**
It might be helpful if the parser can display the path within the RAML where the error occurred. For the previous output, the path must be something like:

`/types/User/example/value/name` for the first line and `/types/User/example/value/lastname` for the second
