### ISSUE TITLE
Nested includes on resource types do not work in some scenarios

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-java-parser#262]
Non-working example:

```
#%RAML 0.8
title: Sample API
resourceTypes:
  - readonly: !include resourcetypes/readonly-resource.yaml

/songs:
  type: readonly
  get:
```

- resourcetypes/readonly-resource.yaml
```
get:
  headers: !include common/headers.yaml
  responses:
    200:
```

- resourcetypes/common/headers.yaml
```
x-application-id:
  required: true
```

In this scenario the header is not being merged on the `get` method of `/songs`
