### ISSUE TITLE
Nested Include with relative path does not pass validation

### ISSUE THREAD

**Issue by michaelkwan** [raml-org/raml-java-parser#265]
Using version 0.8.16

```java
List<ValidationResult> results = RamlValidationService.createDefault().validate(...);
```

Example:
api.raml

```yaml
#%RAML 0.8
title: Sample API
resourceTypes:
  - readonly: !include resourcetypes/readonly-resource.yaml

/songs:
  type: readonly
  get:
```

resourcetypes/readonly-resource.yaml
```yaml
get:
  headers: !include ../common/headers.yaml
  responses:
    200:
```

common/headers.yaml
```yaml
x-application-id:
  required: true
```
