### ISSUE TITLE
Parser does not provides information about multiple inheritance

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-java-parser#268]
Consider following RAML snippet:

``` yaml
#%RAML 1.0 Library
types:
  A:
  B:
  C: 
   type: [ A , B ]
```

This time it parses fine, but there is no way to get information that type `C` extends types `A` and `B` in the public API org.raml.v2.api.model.v10.datamodel.TypeDeclaration - just returns `null` in the type() method (this is probably correct) but there is no way to get multiple ancestors.

Regards,
Pavel
