### ISSUE TITLE
Error parsing correct date with datetime format provided in rfc3339 compliance 

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-java-parser#275]
The following datetime format should be valid:
```
  updated:
    type: datetime
    examples:
      good: 2016-02-28T16:41:41Z # secfrac is optional
```
