### ISSUE TITLE
maximum and minimum facets can't handle > 32-bit numbers

### ISSUE THREAD

**Issue by ggood** [raml-org/raml-java-parser#280]
The java raml parser complains when I have a maximum facet where the value won't fit in a 32-bit signed number. In org.raml.v2.internal.impl.v10.type.IntegerResolvedType, I see:

```
    @Override
    public ErrorNode validateFacets()
    {
        int min = getMinimum() != null ? getMinimum().intValue() : Integer.MIN_VALUE;
        int max = getMaximum() != null ? getMaximum().intValue() : Integer.MAX_VALUE;
```

I'm not aware of any limitations on the size of an integer, so this check seems overly restrictive. For example, the following seems to make sense:

```
      baz_wide:
        type: integer
        format: int64
        maximum: 2147483648
```

Maybe the above code should be using BigDecimal instead of int?

FWIW, the API Workbench Atom plugin doesn't have a problem with this.

On a related note, should the maximum and minimum facets take into account any format facets? For example, does the following make sense? The maximum facet gives a number that won't fit in an 8-bit integer

```
      baz_narrow:
        type: integer
        format: int8
        maximum: 2147483648
```

**Comment by ggood** [comment]
Oh, sorry, the actual error message is:

```
	- Invalid element 2147483648. [line=12, col=18]
```

**Comment by ggood** [comment]
Example RAML file:

```
title: Exercise bug in maximum facet
types:
  Foo:
    type: object
    properties:
      bar:
        type: integer
        maximum: 2147483647  # ok
      baz:
        type: integer
        maximum: 2147483648  # produces error
      baz_wide:
        type: integer
        format: int64
        maximum: 2147483648  # produces error
      urp:
        type: number
        maximum: 2147483648
```
