### ISSUE TITLE
JSON with duplicated keys is considered valid

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#282]
Parsing the following example:

```yaml
#%RAML 1.0
title: Test

types:
  User:
    properties:
      name: string
      age: integer
    example: 
      {
        "age" : 23,
        "name" : "Pepe",
        "age": 20
      }
```

The parser is considering the example valid, though it has duplicated key "age"

**Note:**

As stated in [RFC-7159](https://tools.ietf.org/html/rfc7159#section-4), duplicated keys in JSON are not strictly prohibited:

> The names within an object SHOULD be unique.

Where SHOULD, according to [RFC-2119](https://tools.ietf.org/html/rfc2119), is defined as:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
>    may exist valid reasons in particular circumstances to ignore a
>    particular item, but the full implications must be understood and
>    carefully weighed before choosing a different course.

With this in mind, the parser should provide a mechanism to accept (or not) JSON with duplicated keys.
