### ISSUE TITLE
Don't show absolute "loadingURI" when displaying JSON Schema errors

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#288]
Parsing the following RAML, containing an included JSON Schema:

``` yaml
#%RAML 1.0
title: API with Examples
types:
  User:
    type: !include user.json
    examples:
      bob: |
        {
          "name": 15,
          "age": "Marley"
        }
```

Where `user.json` is defined as follows:

``` yaml
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net",
  "type": "object",
  "properties": {
    "name": {
      "id": "http://jsonschema.net/name",
      "type": "string"
    },
    "age": {
      "id": "http://jsonschema.net/age",
      "type": "integer"
    }
  },
  "required": [
    "name",
    "age"
  ]
}
```

**Actual result**
The parser is giving this output, where `loadingURI` is displaying the absolute path of the included file.

```
       	- Error validating JSON. Error: {
error: instance type (string) does not match any allowed primitive type (allowed: ["integer"])
    level: "error"
    schema: {"loadingURI":"file:/Users/lorenadaicich/MuleSoft/10-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/examples/include-json-schema-multiple-examples/user.json#","pointer":"/properties/age"}
    instance: {"pointer":"/age"}
    domain: "validation"
    keyword: "type"
    found: "string"
    expected: ["integer"]
,
error: instance type (integer) does not match any allowed primitive type (allowed: ["string"])
    level: "error"
    schema: {"loadingURI":"file:/Users/lorenadaicich/MuleSoft/10-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/examples/include-json-schema-multiple-examples/user.json#","pointer":"/properties/name"}
    instance: {"pointer":"/name"}
    domain: "validation"
    keyword: "type"
    found: "integer"
    expected: ["string"]

} [line=7, col=12]
```

**Expected result**
`loadingURI` shouldn't display the absolute path to the included file, only the filename.
