### ISSUE TITLE
Datetime only accepts format with millis

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#314]
As spec states: 
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#date

A timestamp in one of the following formats: if the format is omitted or set to rfc3339, uses the "date-time" notation of RFC3339; if format is set to rfc2616, uses the format defined in RFC2616.

RFC3339
https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

Issue:
The following format is not accepted, it should be added millis in order to work

```yaml
    queryParameters:
      startDate:
        description: Start date time to begin filtering of the results
        required: true
        type: datetime
        example: "2015-08-19T15:10:16Z"
      endDate:
        description: End date time till which result set should be returned
        required: true 
        type: datetime
        example: "2015-10-19T15:10:16Z"

```
