### ISSUE TITLE
[Q] How to get only properties directly declared in an object type?

### ISSUE THREAD

**Issue by tiguchi** [raml-org/raml-java-parser#316]
I'm not sure if this should be just a question or a feature request. I tried to find answers in the source code and by reading through existing issues here, without luck so far.

# Question
I'd like to know if there's a simple way to get a list of properties that are directly declared (or overridden) in an `ObjectTypeDeclaration`, without any inherited (or "resolved") properties from parent types.

# Example
Given the following mock RAML API

```yaml
#%RAML 1.0
title: Mock API
types:
  WithID:
    type: object
    properties:
      id:
        description: Unique object ID.

  User:
    type: WithID
    properties:
      login_name:
        description: User login name.
```

...in Java I would like to do something like that: 
```java
// Let's assume api is the parsed mock API:
List<TypeDeclaration> types = api.types();
ObjectTypeDeclaration userType = (ObjectTypeDeclaration) types.get(1);

// Is there a method like this one anywhere available?
List<TypeDeclaration> declared = userType.declaredProperties();

for (TypeDeclaration declaredProp : declared) {
    System.out.println(declaredProp.name());
}

```
## Expected Output
```
login_name
```

# Use Case
I'm trying to write a Java code generator for creating Java beans. I'd like to generate beans for RAML resource types using Java inheritance, instead of having duplicated code due to resolved properties.

That means I'd like to transform the RAML type declarations into the following Java code:

## WithID.java
```
public class WithID {
    public String id;
}
```

## User.java
```
public class User extends WithID {
    public String login_name;
}
```
