### ISSUE TITLE
Parser should show an error message as default media type is not supported in libraries

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#321]
Root file:

```
#%RAML 1.0
title: Example API
version: v1
mediaType: application/json

uses:
  resourceTypes: resourceTypes.raml
  

/entity:
  get:
```

Library file looks like this:

```
#%RAML 1.0 Library
usage: Standard resourceTypes

resourceTypes:
  item:
    put:
      body:
          example: {"property":"value"}
```

ISSUE:
Right now, the default media type cannot be used by libraries. Parser does not give any feedback when using a RAML file with this characteristics.

Spec issue related: https://github.com/raml-org/raml-spec/issues/592
