### ISSUE TITLE
TypeDeclaration.validate does not work with yaml

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#331]
Given 
````
/url:
  post:
    body:
      mime:
        properties:
          name:
````
Then calling `validate("{\"nam\": \"bla\"}")` on the body's `TypeDeclaration` gives `Error validating JSON. Error: - Missing required field "name"` 

but calling `validate("nam: bla")` gives no error message
