### ISSUE TITLE
!singularize function does not resolve "media" correctly

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#333]
Parsing the following RAML:

```yaml
#%RAML 1.0
title: Test

types:
  PostMedia:
    type: object
    properties:
      name: string

resourceTypes:
  collection:
    post?:
      body:
        application/json:
          type: Post<<resourcePathName | !singularize | !uppercamelcase>>

/media:
  type: collection
  post:
    body:
      application/json:
        example:
          name: "Something"
```

_Throws the following error:_
> 
> 1 error found:
>         - Invalid reference 'PostMedium' [line=0, col=0]

_Expected output:_
Parsing must be done successfully
