### ISSUE TITLE
resourcePathName is not being resolved correctly

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#334]
Parsing the following RAML:

```yaml
#%RAML 1.0
title: Test

types:
  Login:
    type: object
    properties:
      name: string

resourceTypes:
  collection:
    post?:
      body:
        application/json:
          type: <<resourcePathName | !singularize | !uppercamelcase>>

/user/login:
  type: collection
  post:
    body:
      application/json:
        example:
          name: "Something"
/other:
  /login:
    type: collection
    post:
      body:
        application/json:
          example:
            name: "Something"
```

_Throws the following error:_

> 1 error found:
>         - Invalid reference 'User/login' [line=0, col=0]

This just happens when the resource is defined as `/user/login` (in the same line), but not when there are two resources: One for `user` and the oher for `login`

_Expected output:_
RAML must be parsed successfully
