### ISSUE TITLE
Enum on number type make the parser fail

### ISSUE THREAD

**Issue by boillodmanuel** [raml-org/raml-java-parser#342]
With parser 1.0.6, the following file fails
```
#%RAML 1.0

title: API
version: v1
types:
  Number:
    type: number
    enum:
    - 0
    - 1
    - 2
    default: 0
```

with message `Invalid facets for type ClientType: enum values must be between 0 and 1`

adding 
```
    minimum: 0
    maximum: 2
```
will make it work
