### ISSUE TITLE
Parser accepts negative values under 'minLength' and 'maxLength' facets

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#345]
According to the RAML 1.0 spec, the description for **minLength** and **maxLength** facets is:

> Specifies the minimum number of bytes for a parameter value. The value MUST be equal to or greater than 0.

But the following RAML is considered valid:

``` yaml
#%RAML 1.0
title: Test
types:
  Email:
    type: string
    minLength: -2
    maxLength: 6
```

**Expected result**:
Parser MUST only accept values equal to or greater than 0 for min/maxLength facets
