### ISSUE TITLE
property `fileTypes` is not imported

### ISSUE THREAD

**Issue by boillodmanuel** [raml-org/raml-java-parser#352]
Hi,

With parser 1.0.6, the `fileTypes` attribute is not imported. 
Tested with the spec example:

```
#%RAML 1.0
title: API with Examples

types:
  userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/png']
    maxLength: 307200
```
