### ISSUE TITLE
Error parsing XML schemas with relatives schema locations in RAML 1.0

### ISSUE THREAD

**Issue by dlarralde** [raml-org/raml-java-parser#388]
**Scenario**
The [project](https://github.com/raml-org/raml-java-parser/files/1077518/nested-relative-xmlschema.zip) consist of the following root RAML

```
#%RAML 1.0
title: testXML
version: 1.0

/api/request:
  post:
    body:
      application/xml:
        type: !include dir/subdir1/request.xsd
        example: !include example.xml
```

The body declaration type points to the following XML schema

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://raml.org/subdir1/request"
           xmlns:tns="http://raml.org/subdir1/request"
           xmlns:message="http://raml.org/subdir2/message"
           elementFormDefault="qualified">

    <xs:import namespace="http://raml.org/subdir2/message" schemaLocation="../subdir2/message.xsd" />

    <xs:element name="Request">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Header" type="message:Header" />
                <xs:element name="Payload" type="message:Payload" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
```
As we can see this schema imports types from a relative schema file.

**Actual behavior:**
The parser fails to resolve XML schema
```
- Error validating Schema. Error: src-resolve: Cannot resolve the name 'message:Header' to a(n) 'type definition' component. [line=7, col=11]
```
**Expected behavior:**
From RAML 1.0 spec
> A RAML processor MUST be able to interpret and apply JSON Schema and XML Schema.
