### ISSUE TITLE
Exception thrown validating RAML 1.0 with boolean discriminator

### ISSUE THREAD

**Issue by aamura** [raml-org/raml-java-parser#404]
Validating this RAML
```
#%RAML 1.0
title: Sample API
version: v1
baseUri: http://apis.cscglobal.com/sample/api
mediaType: application/json
types:
  ValueListType:
    type: object
    properties:
      id: string
      label: string
      external: boolean
    discriminator: external

  KnowledgeValueListType:
    type: ValueListType
    discriminatorValue: false

  ExternalValueListType:
    type: ValueListType
    properties:
      externalDataType: string
    discriminatorValue: true

traits:
  paged:
    queryParameters:
      max:
        description: The number of items to display
      offset:
        description: The offset from the first result to list from
```
Produce this Exception:
java.lang.Boolean cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
at org.raml.yagi.framework.util.NodeSelector.selectStringValue(NodeSelector.java:99)
at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.overwriteFacets(ObjectResolvedType.java:133)
at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.resolveTypeDefinition(TypeDeclarationNode.java:99)
at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.getResolvedType(TypeDeclarationNode.java:85)
at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.validateCanOverwriteWith(ObjectResolvedType.java:209)
at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.validateCanOverwrite(TypeDeclarationNode.java:143)
at org.raml.v2.internal.impl.commons.phase.TypeValidationPhase.apply(TypeValidationPhase.java:48)
at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:95)
