### ISSUE TITLE
Missing query parameters from traits

### ISSUE THREAD

**Issue by dc950** [raml-org/raml-java-parser#411]
I've come across an issue (using version `1.0.12`) where query parameters from traits are not present in the model under certain conditions.

It seems to be related to the parameters being defined as not required using a `?` and the order of the traits in the `is`.

With the following raml spec:

```
#%RAML 1.0
title: test
baseUri: /test

traits:
  trait1:
    queryParameters:
      t1?:
        type: string
  trait2:
    queryParameters:
      t2:
        type: string
        required: false

/test:
  get:
    is: [trait1, trait2]
  put:
    is: [trait2, trait1]
```

And the following java code just to look at the query parameters:

```
class Main {
  public static void main(String[] args) {
    RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi("test.raml");
    Api api = ramlModelResult.getApiV10();
    for(Resource res : api.resources()) {
      for(Method method : res.methods()) {
        System.out.println("\nMethod: " + method.method());
        System.out.println("Number of query parameters: " + method.queryParameters().size());
        for(TypeDeclaration param : method.queryParameters()) {
          System.out.println("  - " + param.name());
        }
      }
    }
  }
}
```
The output is this:
```
Method: get
Number of query parameters: 2
  - t1
  - t2

Method: put
Number of query parameters: 1
  - t2
```
Also, setting `t2:` to be `t2?:`  and removing the `required: false` makes both methods contain only 1 of the parameters:

```
Method: get
Number of query parameters: 1
  - t1

Method: put
Number of query parameters: 1
  - t2
```
