### ISSUE TITLE
Number example of a type with 'multipleOf' throws "Can not divide by 0"

### ISSUE THREAD

**Issue by dlarralde** [raml-org/raml-java-parser#427]
The parser fails to process the following RAML because of a runtime exception ( "Can not divide by 0")

```
#%RAML 1.0

title: Test

types:
  Foo:
    properties:
      amount:
        type: number
        multipleOf: 0.01
        examples:
          valid1: 100.22
          valid2: 100.0 
          valid3: 100        # <--- throws 'Can not divide by 0'
```
The exception arises when it tries to validate the value of the example 'valid3'.

According to the RAML 1.0 spec:

> A numeric instance is valid against "multipleOf" if the result of dividing the instance by this keyword's value is an integer.

As 100 / 0.01 is an integer the validation should pass but the validation fails.
