### ISSUE TITLE
Properly reporting base uri in validation results

### ISSUE THREAD

**Issue by gardea** [raml-org/raml-java-parser#43]
I have the following layout (I am using the test files, renamed include-sequence.yaml to *.raml):

![layout](https://cloud.githubusercontent.com/assets/8659307/4414874/08014fc4-4521-11e4-8420-1d0c257fe03a.png)

I've added an empty description in sequence-trait.yaml:

```
paged:
    queryParameters:
        offset:
            description:
            type: integer
            default: 0
        limit:
            type: integer
            default: 10
secured:
    headers:
        security:
            type: boolean
            required: true

```

When validating include-sequence, a warning (validation result) shows up, saying description cannot be empty; the line/col is reported as 4/13.

However, through the validation result object, I couldn't trace the base uri of the file for which the line/col applies (in this case it should be sequence-trait.yaml).

Is there a way to resolve the offending uri?

Aha! Link: https://mulesoft-roadmap.aha.io/features/APIRAML-150
