### ISSUE TITLE
Problem overriding inherited properties 

### ISSUE THREAD

**Issue by stojsavljevic** [raml-org/raml-java-parser#480]
Hi,

first of all, thanks for your great work!
I'm using your library for `springmvc-raml-plugin` project and it works great.

But today I discovered one problem with data types and inheritance.
Consider this data type definition:
```
...
types: 
  Person:
    type: object
    properties: 
      firstName: string
  User:
    type: Person
    properties: 
      userId: integer
      firstName:
        default: Alex
```

When parsing this raml using `raml-parser-2` v.1.0.18 I can't get default value for `firstName` property of `User`. `defaultValue()` method returns `null`.
The very same thing happens with other attributes like `example`, `description` etc.

If I remove `firstName` definition from `Person` type, everything works as expected.

If I'm not mistaken I should be allowed to inherit and override type's attributes.
