### ISSUE TITLE
Unexpected key error when having global mediaType

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#498]
Given the following RAML
```
#%RAML 1.0

title: API Manager
mediaType: application/json

resourceTypes:
  collection:
    post:
      body:

/resource:
  type: collection 
  post:
    body:
      application/json:
        type: string
```

An "Unexpected key error" is thrown.

Because `mediaType` is defined globally, when applying `GrammarPhase` to `collection` the node `type` and `displayName` gets appended under `body`. When the type `collection` gets merged with the `post` of `/resource` this nodes (`type` and `displayName`) gets merged too. 
And because `application/json` is defined as the `body` of `resource` the `MediaTypeInjectionPhase` does not move those nodes under `application/json`.
