### ISSUE TITLE
Error merging media types from resoruceType

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-java-parser#501]
this raml
```
#%RAML 1.0

title: API Manager

resourceTypes:
  collection:
    post:
      body:
        application/json:

/tiers:
  type: collection
  post:
    body:
      text/xml:
```
fails with the following error:
```
"Unexpected key 'application/json'. Options are : "default" or "description" or ...
```
