### ISSUE TITLE
Issue with parsing nested URI's

### ISSUE THREAD

**Issue by stevendavelaar** [raml-org/raml-java-parser#53]
I am using the RAML Parser for Java, and validation fails on a nested URI that follows the spec. Can be reproduced using this RAML sample which is directly copied from the spec:

#%RAML 0.8
title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]
    get:
      displayName: retrieve a user's picture
    put:
      displayName: update a user's picture
      baseUriParameters:
        apiDomain:
          enum: [ "content-update" ]

The RAML validator  gives an error on lines 15 and 17:
Unknown key: displayName

**Comment by stevendavelaar** [comment]
(Indentation is lost while copying, unfortunately)

**Comment by ddossot** [comment]
Copied with format from the [spec source](https://raw.githubusercontent.com/raml-org/raml-spec/master/raml-0.8.md):

```
#%RAML 0.8
title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]
    get:
      displayName: retrieve a user's picture
    put:
      displayName: update a user's picture
      baseUriParameters:
        apiDomain:
          enum: [ "content-update" ]

```
