### ISSUE TITLE
Exception thrown when having an example with a value greater than Long.MAX_VALUE

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#536]
Given this RAML:

```
#%RAML 1.0
title: Exception when format

types:
  LongNumber:
    type: number
    format: long
    minimum: 1
    maximum: 9223372036854775807
    
  ObjectType:
    type: object
    properties: 
      property: LongNumber
    examples:
     -example: | 
       { "property":12345678901234567890 }
```

An exception is thrown when parsing it.
