### ISSUE TITLE
Incorrect error when having an example with a number greater than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#538]
Given this RAML:

```
#%RAML 1.0
title: Error message

types:
  Number:
    type: integer
    format: int64
    minimum: 1
    maximum: 9999999999
    
  ObjectType:
    type: object
    properties: 
      property: Number
    example: | 
      { "property":9999999999 }
```

This message is thrown:

`- Error validating JSON. Error: - Invalid type Float, expected Integer for property`

When property value is an integer.
