### ISSUE TITLE
Wrong names for arrays properties in autogenerated XSDs

### ISSUE THREAD

**Issue by dfmacias** [raml-org/raml-java-parser#540]
Given the following raml:
```
#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friends: Friend[]
    additionalProperties: false
  Friend:
    type: object
    xml:
      name: Friend
    properties:
      name: string
    additionalProperties: true
```
Raml parser is generating the following schema for types
```
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://validationnamespace.raml.org" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://validationnamespace.raml.org">
    <element name="root" type="tns:root"/>
    <complexType name="root">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string"/>
                </simpleType>
            </element>
            <element maxOccurs="unbounded" name="Friend" type="tns:Friend"/>
        </sequence>
    </complexType>
    <complexType name="Friend">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string"/>
                </simpleType>
            </element>
            <any maxOccurs="unbounded" minOccurs="0" processContents="skip"/>
        </sequence>
    </complexType>
</schema>
```

When the following schema is expected:
```
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://validationnamespace.raml.org" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://validationnamespace.raml.org">
    <element name="root" type="tns:root"/>
    <complexType name="root">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string"/>
                </simpleType>
            </element>
            <element maxOccurs="unbounded" name="friends" type="tns:Friend"/>
        </sequence>
    </complexType>
    <complexType name="Friend">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string"/>
                </simpleType>
            </element>
            <any maxOccurs="unbounded" minOccurs="0" processContents="skip"/>
        </sequence>
    </complexType>
</schema>
```
