### ISSUE TITLE
When having an error in library, file path information is not available

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#542]
```
#%RAML 1.0
title: Example
uses:
  Library: library.raml
```

```
#%RAML 1.0

errror on purpose
types:
  Person:
    type: string
```

After parsing it, when doing errorNode.getStartPosition().getPath() an empty string is returned when it should return the path of the library imported.
