### ISSUE TITLE
Exception when using discriminator

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#547]
root.raml

```
#%RAML 1.0
title: discriminator-test

uses:
  partyTypesLibrary: partyTypesLibrary.raml
```

partyTypesLibrary.raml

```
#%RAML 1.0 Library
types:
  party:
    type: object
    discriminator: kind
    properties:
      id:
        type: string  
        required: false
      kind:
        type: string
        required: true
        
  naturalPerson:
    type: party
    properties:
      salutation:
        type: string
        required: true
    example:
      id: "1213"
      salutation: "Dhr."
      kind: naturalPerson
```

When parsing the above RAML an exception is thrown
