### ISSUE TITLE
queryParameters in nested traits are not handled well

### ISSUE THREAD

**Issue by techpavan** [raml-org/raml-java-parser#558]
Nested traits are not parsed while processing the `queryParameter` property.

Reproducer: https://github.com/techpavan/raml-java-parser-issues/tree/master/1

Below are the raml and parsing result from reproducer for quick reference:

**RAML**
```
traits:
  trait1:
    queryParameters:
      param1:
        type: string
      param2:
        type: string
        required: false

  trait2:
    is: trait1



/resource1:
  get:
    is: trait1

/resource2:
  get:
is: trait2
```

**Output**
 ```
Path: /resource1
	Parameter: param1
	Parameter: param2

Path: /resource2
```
