### ISSUE TITLE
Exception when validating against union or array type

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#569]
Given this raml

```
#%RAML 1.0
title: test validate
/resource:
   get:
     queryParameters:
        union-type:
          type: object | string
        array-type:
          type: number[]
```

when trying to validate against TypeDeclaration of items() (in case of array), or of() (in case of union) an exception is thrown in `validate()` method in `TypeDeclaration`
