### ISSUE TITLE
Generated JSON Schema does not include default value

### ISSUE THREAD

**Issue by james-thomson** [raml-org/raml-java-parser#571]
Given the following raml
```
#%RAML 1.0
title: no default
types:
  fooType:
    default: 'foo'
```
calling toJsonSchema() on the TypeDeclaration for fooType produces the json schema
```
{
  "type": "string",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```
It would be good if the default value was included in the generated json schema.

Aha! Link: https://mulesoft-roadmap.aha.io/features/APIRAML-45
