### ISSUE TITLE
'uses' not recognised when type treated as inline type on property

### ISSUE THREAD

**Issue by tapina** [raml-org/raml-java-parser#572]
Parsing validation fails if your RAML has the following structure:

*Top level*
```yaml
%RAML 1.0
..
types:
  mytype:
    type: !include types/mytype.raml
```

*Data type*
```yaml
%RAML 1.0 DataType
uses:
  mylib: ../../lib.raml

type: object
properties:
  myproperty: !include myproperty.raml
...
```
*Property type*
```yaml
%RAML 1.0 DataType
uses:
  mylib: ../../lib.raml

...
```

Validation failed saying that uses is unexpected.

This is because the property type is treated as purely inline rather than an external type declaration and so 'uses' is not an expected field.

See the attached patch for a fix.
[fix_uses.patch.txt](https://github.com/raml-org/raml-java-parser/files/2644776/fix_uses.patch.txt)
