### ISSUE TITLE
Error when property is a number

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#584]
Error when parsing:
```
#%RAML 1.0
title: Test!

types:
  type-with-number:
    type: object
    properties:
      214:
        displayName: "214"

/reosurce:
  get:
    body:
      application/json:
        type: type-with-number
```
