### ISSUE TITLE
datetime-only fails when having fractions of secons

### ISSUE THREAD

**Issue by pacafuentes** [raml-org/raml-java-parser#587]
```
type: datetime-only
examples:
   good2: 2015-07-04T21:00:00.0000
   good3: 2015-07-04T21:00:00.0
```

Should be valid
