### ISSUE TITLE
Protocols validation should be case insensitive

### ISSUE THREAD

**Issue by jpbelang** [raml-org/raml-java-parser#591]
This fails parsing:

```yaml
#%RAML 1.0
title: Example
protocols:
  - http
```
