### ISSUE TITLE
Years in datetime-only can be longer that 4 digits

### ISSUE THREAD

**Issue by jpbelang** [raml-org/raml-java-parser#600]
As an side effect of issue #588, years can have more than four digits.

**Comment by jpbelang** [comment]
```
#%RAML 1.0
title: RAML Proxy
version: v1

types:
    fireworks:
        type: date-only # no implications about offset
        examples:
            bad1: 20151-07-04T21:00:00.0
            bad2: 20151-07-04T21:00:00
```
