### ISSUE TITLE
Numbers shouldn't be validated if they are strings

### ISSUE THREAD

**Issue by jpbelang** [raml-org/raml-java-parser#610]
```yaml
#%RAML 1.0
title: Integer type test
/resource:
  get:
    queryParameters:
      integer-range-type-fail:
        type: number
        minimum: 0
        maximum: 9999
        example: "37"
      integer-type-fail:
        type: number
        example: "37"
```
