### ISSUE TITLE
Ranges (minimum and maximum) should be able to mix types

### ISSUE THREAD

**Issue by jpbelang** [raml-org/raml-java-parser#611]
Like so:
```yaml
#%RAML 1.0
title: Integer type test
/resource:
    get:
        queryParameters:
            integer-range-type-fail:
                type: number
                minimum: 0
                maximum: 9999.0
                example: 37
```
