### ISSUE TITLE
Discriminator sub-datatype validates to anything

### ISSUE THREAD

**Issue by jam01** [raml-org/raml-java-parser#620]
Consider the following RAML
```
types:
  event:
    type: object
    discriminator: eventType
    properties:
      eventType: string

  fooEvent:
    type: event
    discriminatorValue: foo
    properties:
      bar: string

/resource:
   post:
     body:
       application/json:
         type: fooEvent
```

**Expected behavior**
resource/ should accept a value such as:
`{"eventType":"foo", "bar":"val"}`

and reject a value such as:
`{"not":"acceptable"}`

**Current behavior**
Both are considered valid.

Seems to me the issue is that unless the discriminator field is present there's no validation at all and everything is valid. 

There should be a validation that the discriminator field exists and then check for valid values of that field and validate accordingly, otherwise it should fail.

I added test cases in this PR https://github.com/raml-org/raml-java-parser/pull/602
