### ISSUE TITLE
Example does no validate properly when included

### ISSUE THREAD

**Issue by jpbelang** [raml-org/raml-java-parser#632]
```yaml
#%RAML 1.0
title: My Sample API

types:
  SomeType:
    type: object
    properties:
      a: string
      b: integer
    examples: !include example.raml
example.raml:
```
```yaml
#%RAML 1.0 NamedExample

value:
  a: blabla
  b: 111
```

This does not validate.
