### ISSUE TITLE
datetime-only validation

### ISSUE THREAD

**Issue by juanchib** [raml-org/raml-java-parser#660]
```
#%RAML 1.0
title: test API
version: v1.0

/dateTimeOnlyValidation:
  post:
    description: validate dateTimeOnly type with border date values
    body:
      application/json:
        type: datetime-only 
        example: 2014-02-238T16:41:41.00 
```

Validation for the example should throw an error. At 1.0.30 it works as expected but on later versions it doesn't throw any exception.
