### ISSUE TITLE
Type is not inferred from property `fileTypes`

### ISSUE THREAD

**Issue by martincousido** [raml-org/raml-java-parser#669]
Similarly to the property properties of the "Object" type, the "File" type should be inferred when the property fileTypes is defined (and the type is not set).

Example:
```
#%RAML 1.0
title: Use_Case_5

types:
  fireworks:
    description: This is a new DataType
    fileTypes:
      - image/gif
```
